# Generated by Django 5.0.6 on 2024-06-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solaris_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rut',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
