# Generated by Django 5.0.6 on 2024-06-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solaris_app', '0002_user_rut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energyproduction',
            name='amount',
        ),
        migrations.AddField(
            model_name='energyproduction',
            name='accumulated_energy',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='energyproduction',
            name='efficiency',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='energyproduction',
            name='power_generated',
            field=models.FloatField(null=True),
        ),
    ]
