# Generated by Django 5.0.6 on 2024-06-06 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solaris_app', '0003_remove_energyproduction_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenancealert',
            old_name='alert_message',
            new_name='message',
        ),
        migrations.AddField(
            model_name='maintenancealert',
            name='energy_production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solaris_app.energyproduction'),
        ),
        migrations.AddField(
            model_name='maintenancealert',
            name='title',
            field=models.CharField(default='Maintenance Alert', max_length=100),
        ),
    ]
