# Generated by Django 5.0.6 on 2024-06-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solaris_app', '0004_rename_alert_message_maintenancealert_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('operational', models.BooleanField(default=True)),
                ('power_output', models.FloatField(help_text='Power output in kW')),
                ('last_inspection', models.DateField()),
            ],
        ),
    ]
