# Generated by Django 5.0.6 on 2024-07-09 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solaris_app', '0006_passwordresetcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solarsystem',
            name='location',
        ),
        migrations.AddField(
            model_name='solarsystem',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
