# Generated by Django 5.0.6 on 2024-07-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solaris_app', '0007_remove_solarsystem_location_solarsystem_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='SolarSystem',
        ),
    ]
